matrix:
  include:
  - os: linux
    env: BUILDARCH=x64
    dist: trusty
  - os: osx
  - os: windows
language: node_js
node_js: '13'
before_script: "./scripts/build.sh"
script: "./scripts/testAll.sh"
notifications:
  slack:
    secure: IVKQI4QJkJOi1qVR+U88khCwjeTgIXBt7R6auLwIBHuELsQzbvclwW0nWlmgwCHethaiw2Q4J73pzYHLPMidANJD+M1UubpL+N1YWjlDjwvINjwhUylXdRWfCIkCXapFUmAiPgrZGIP0k5Rxw/tdA05HeYyuZ4F0R/8SnGR/lt8NAFBK5QJirU7wiKA9LbCIqMq5UwiA7PuyCwfX68gcKMrbcHr3uHpLNqZtHlk//P+PZqhUGPqfTCMFRS5FWxWhFDyK8lN56cexMx2Zza/J5W1b4oSZbJZWt/tv7GonedWnf6PfOsztA5IS/mkciWpYlrb5fgnqDHF4nsT/5Ia99wgF37XaS8gONK7XhokkV1nmtA51qcj5LvKOThyf99HpAgDeinlH7b7FZXsiUrH43OQGtYbMAj7wXu1x9D9hbtw00tA6OnumqYuTyUol4ez1HtQ/3L8V+rU5JAe+9hi4kQE++w2cky0uEH0FK68e1J9UP24AYSilLbGG35EZSnbVKl7CXrPhec4im+ftrBihw9Uv/PRpCta3ePD+k68ZNyUeX+SZOKDsS8ZLImDMOJ44+wyirjKbEzKiR5M6m5uNLXeQjt5DLr0WcTqSTvb0Fo4jQ6csZ8XAIcz20BIiE6DeCAXYQBJmvMJI1zRjdp/SqMmXd5OoJjXhxUxRy+7VRHs=
