matrix:
  include:
  - os: linux
    env: BUILDARCH=x64
    dist: trusty
  - os: osx
  - os: windows
language: node_js
node_js: '13'
install:
- |
  if [ $TRAVIS_OS_NAME == "linux" ]; then
    export DISPLAY=':99.0'
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  fi
before_script: "./scripts/build.sh"
script: "./scripts/testAll.sh"
notifications:
  slack:
    secure: tP93nhwYNa22dx1hMx4wtYzScHM1tIGIOz0jCjm8oTbTjUp8W+U95p6IxYzw7tpuc2XkcA7soIxVMtaNEbMQPPw+LL9LHLRlRhvzLhsxtQ020ye9+eYei3u7/XUupUvCNjo8DMeNEBEUiVhIfcnUy9A8yn+dLd67MKwlM2TpUS1n0VfcajXbDl7pRt8XDzXkjzUx4al2qVCBHhCwcz59qrHWvsQWfOyFsVELawb9dWs5rNJ2rJg6xeo3Cd2idBgzq0mqITiJHjRsNtqtjjVu3GK3S4ypIi9JbLdNI/oHJH+4CngwyNl/Su9W4J+13xpQRBn0fMRHGVhj7NRBLyx2jLx//JJ26X7gg68Yv7tV8Wq1pGTRyJve8D7aDBx51PjrK0DJP5Q8ecGt+i3kGDrDfO2vftj6U0gP3tunsX+288e53gqaWbTt0Qf2RD7HtNYMouHRLxJvfdjw16a71IDJKdxPw0DNk928fx5E+S/VcuXYQK9ufvx0rz6LMQkBudVXBcmYT+3MJTYFkiT7NJmBurcLX+QA4E1VL0jK2yJQnj67HMZ2zBYPayL+5GezSytsNqgkEREcWONjFCVePuqjhUTs+l07sUD+njMY06dnZ4GpTu7aO/UkjM3WnSsoSUxXHDPEEvFjBzCCTL2JKW6jDN7/4O5RzGsCgSk77X6pOI8=
env:
- YARN_GPG=no
cache: yarn
