- hosts: localhost # use all for remote
  tasks:
    - name: copy header
      template:
        src: ../templates/_readme.header.j2
        dest: ../docs/README.md
    - name: append newline
      shell: echo "\n" >> ../docs/README.md
    - name: append readme
      shell: cat ../README.md >> ../docs/README.md